name: ai_profanity_textfield
description: "A textfield widget that checks for profanity in the input text."
version: 1.0.0
homepage: https://github.com/MCHTSEN/ai_profanity_textfield
repository: https://github.com/MCHTSEN/ai_profanity_textfield

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
